### ISSUE TITLE
Preset alongside theme extender

### ISSUE THREAD

**Issue by catuhana** [catuhana/unocss-catppuccin#3]
As with [`5903c74`](https://github.com/tuhanayim/unocss-preset-catppuccin-colors/commit/5903c740e0f0b12e47601caf535a9bcdf1b3d7c3), this project doesn't provide any preset for UnoCSS. Adding preset back *(with #1 and #2 support)* might be a good addition, but I personally think it isn't needed.

**Comment by tuhanayim** [comment]
Won't be fixed unless contributed. Creating a preset just for colour scheme is a waste of time, since the same thing can be achieved by extending themes in UnoCSS's `theme.colors` options.

Also, it won't support all other preset features, they need to be worked on and implemented manually *(things such as custom variants can be implemented easily by adding an option to the preset though)*.

**Comment by tuhanayim** [comment]
It will be implemented when I'm not on my lazy days.

**Comment by catuhana** [comment]
I have finally decided that we don't need this. All colours in UnoCSS presets are being put under `theme` object, instead of having rules that specify which colour should be used. Instead of having our own set of rules that define which colour should go where, we should specify the colours that exist to the preset.
